### ISSUE TITLE
Error or missing steps on installing on 24.1

### ISSUE THREAD

**Issue by jmolina-in** [lschilde/Sharing_APEX_SERT_24_1#2] opened 2024-10-28 22:10 UTC
![image](https://github.com/user-attachments/assets/e080df65-8eb6-45c7-8994-eede63239906)
On running the installer  as sys I got the result in the image, I can see the admin app, but the error logs page shows :
"object line object handle number name 0xb28e4e80 146 package body SV_SERT_240100.SV_SEC_SCHEDULER.RUN_SCHED_EVALS". Also,  the APEX-SERT application shows the session expired message anytime being launched, I'll appreciate any feedback o documentation, maybe I am missing something. Thanks

**Comment by lschilde** [comment] 2024-10-28 22:57
Hey, appreciate the message. From what I see in this image, there is an
issue with auto_setup parameters, check them again, it is not able to
connect to this line

connect SV_SERT_LAUNCHER/^schema_password@^db_conn_string

Trouble is that without it the app will not start. So either uninstall and
install with the above fixed, or you can run that script manually.
@@app/_install_ws.sql apex-sert_launcher_part2.sql


Please let me know how you go, it should not be hard to do this one. Result
should be that the REST API is created under SV_SERT_LAUNCHER schema. Once
it is there the app should be able to start.

**Comment by jmolina-in** [comment] 2024-10-29 04:49
I run the fix and now the app is launched, thanks. However there is an error on computation on page 112, when I try to run an evaluation, this is:

![image](https://github.com/user-attachments/assets/0213dad6-53fc-4321-b503-d1357c2ff996)

**Comment by lschilde** [comment] 2024-10-29 05:13
okay this one is an interesting one.... to solve it we would have to debug where and why it is failing. What type of evaluation are your running or is it just the one which scans the whole app? You have some data in there that it doesn't like and we need to figure out what is causing it to fail. First step would be a print screen if it is failing on a certain page, as this is quite a generic error. There is some data which it doesn't like when creating scorecards (collection) in your app. either a character conversion error or some sort of data type issue. Can you try creating a simple demo app 1/2 pages see if it can score it? If it does try one of your simpler apps... if it works we will have to dig deeper into this issue to figure it out

**Comment by jmolina-in** [comment] 2024-10-29 19:18
Hi,

What type of evaluation are you running or is it just the one which scans the whole app?
This error shows up during evaluation processing. I picked an application in the workspace and clicked evaluate, and the dialog started showing the percentage. Before 10% or 20%, the process crashed, and I went in debug on the SERT workspace and got the previous post error.

I tried using a simple page app with a report and went through the evaluation process to 100%. 

So, do you recommend going deeper into debugging SERT?

Thanks.

**Comment by lschilde** [comment] 2024-10-29 22:54
In its core is actually very simple, we just need to find what causes it problems. Usually when you have a value like &P13_ID. somewhere where code doesn't expect it it breaks Query (on collections) that are used for scoring. Now it is just a matter of finding which of the scoring is dying on you and fix will be 2 min work.

**Comment by lschilde** [comment] 2024-10-29 23:21
If we all want to contribute to the project this is a perfect use case :D. No seriously, I think it is worth looking into it. You got over the hurdle installing it, this part should be easier. 

Please check logger_log entry it created when you tried running it. This is gold to give us clues where the issue is. 

Also it is great that simple app is working means it is one of your app settings which is causing this issue and now we need to find it.

**Comment by lschilde** [comment] 2024-10-29 23:28
We need to find a collection_name and attribute_set_id from logger and this will give us what is wrong with it

**Comment by jmolina-in** [comment] 2024-10-30 14:50
hi Lino, thanks for your support,
 
The point I got is that the error is produced in the package SV_SEC_COLLECTIONS procedure "create_collection" triggered by the code for an app computation (G_SCORE) in app 102 APEX-SERT, that when inserting using a select, the select runs ok so I suspect some field is being overflowed or the data have with a different type.

**Comment by lschilde** [comment] 2024-11-04 23:19
`sv_sec_rules.check_item_syntax(region_header_text || region_footer_text) AS result`

--Collection name = SV_XSS_REG_HEAD_FOOT 
-- LINE MORE THAN 4000 characters in the concatenation, even though check_item_syntax is receiving a CLOB, SQL cant manage more than 4k

Solution is to make MAX_STRING_SIZE  DB parameter = EXTENDED 

SERT code has been updated to cater for this now.

**Comment by lschilde** [comment] 2024-11-20 05:30
reported back and tested working so closing down

**Closed as completed** 2024-11-20 05:30 UTC
